### ISSUE TITLE
Invoking --enable-pub-sub surfaces error "Unrecognized command line argument"

### ISSUE THREAD

**Issue by rpcme** [awslabs/aws-iot-device-client#181] opened 2021-10-18 18:08 UTC
**Describe the bug**

Cannot run pubsub with --enable-pub-sub command line argument

**To Reproduce**

```bash
./aws-iot-device-client --enable-sdk-logging                         --endpoint $(aws iot --profile work --region us-east-1 describe-endpoint --endpoint-type iot:Data-ATS --output text --query endpointAddress)                         --enable-fleet-provisioning true --enable-pub-sub true --publish-topic dc-pub-topic --subscribe-topic dc-sub-topic                       --cert ${credpath}/28eb7244-978a-4376-b81b-1bf9c0cad826.crt.pem                         --key ${credpath}/28eb7244-978a-4376-b81b-1bf9c0cad826.key.prv.pem                         --root-ca ${credpath}/root-ca.pem                         --thing-name $(uuidgen)                         --fleet-provisioning-template-name fp-template-claim 
2021-10-18T05:37:23.925Z [ERROR] {Config.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Unrecognised command line argument: --enable-pub-sub ***
```

**Expected behavior**

Run the pubsub demo

**Actual behavior**

Fatal error

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferably, you can also [increase the verbosity of the logs](https://github.com/awslabs/aws-iot-device-client#logging).

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Architecture: x86-64
 - Device Client commit: 0cae46162cbe2f10205bc2afbe523f368f3a7783

**Additional context**

**Comment by HarshGandhi-AWS** [comment] 2021-12-09 23:19
Hello @rpcme , again thank you for reaching out to us with this issue. @marcoemorais-aws has released the [bug fix](https://github.com/awslabs/aws-iot-device-client/pull/198) for this issue. Please review and test it to see if the issue is resolved for you or not. 
I am resolving this issue now, please feel free to reopen it if the issue is not resolved or open a new issue with us if you are facing any difficulty using the Device Client.

Regards, 
Harsh Gandhi

**Closed by HarshGandhi-AWS** 2021-12-09 23:19 UTC
Labels: bug
