### ISSUE TITLE
Logging target override doesn't change SDK logging

### ISSUE THREAD

**Issue by rpcme** [awslabs/aws-iot-device-client#175] opened 2021-10-15 14:04 UTC
**Describe the bug**

Invoked device client with config file, which has the following configuration

```json
	"logging": {
		"level": "DEBUG",
		"type": "FILE",
		"file": "/var/log/aws-iot-device-client.log"
	},

```

Output of SDK log is in a different directory

```text
2021-08-04T15:14:52.711Z [DEBUG] {Config.cpp}: Did not find a runtime configuration file, assuming Fleet Provisioning has not run for this device
2021-08-04T15:14:52.711Z [INFO]  {Main.cpp}: Now running AWS IoT Device Client version v1.4.0
2021-08-04T15:14:52.717Z [INFO]  {SharedCrtResourceManager.cpp}: SDK logging is enabled. Check /var/log/aws-iot-device-client/sdk.log for SDK logs.
2021-08-04T15:14:52.718Z [DEBUG] {Retry.cpp}: Retryable function starting, it will retry until success
```

**To Reproduce**

1. run device client with different logging target in configuration

**Expected behavior**

both aws iot device client and sdk log are in the same directory

**Actual behavior**

aws iot device client log is in /var/log, but sdk log is in different
directory as shown in the aws iot device client log output

**Logs**

If applicable, add full logs of errors and outputs to help explain your problem. Preferably, you can also [increase the verbosity of the logs](https://github.com/awslabs/aws-iot-device-client#logging).

**Environment (please complete the following information):**
 - OS: Linux
 - Version 1.4.0
 - Architecture: x86-64, RISC-V
 - Device Client commit: 1.4.0 tag

**Additional context**

**Comment by HarshGandhi-AWS** [comment] 2021-12-09 23:20
Hello @rpcme , again thank you for reaching out to us with this issue. @marcoemorais-aws has released the [bug fix](https://github.com/awslabs/aws-iot-device-client/pull/199) for this issue. Please review and test it to see if the issue is resolved for you or not. 
I am resolving this issue now, please feel free to reopen it if the issue is not resolved or open a new issue with us if you are facing any difficulty using the Device Client.

Regards, 
Harsh Gandhi

**Closed by HarshGandhi-AWS** 2021-12-09 23:20 UTC
Labels: bug
