### ISSUE TITLE
Incorrect permissions on created files when using fleet provisioning

### ISSUE THREAD

**Issue by JustinBerger** [awslabs/aws-iot-device-client#301] opened 2022-07-22 19:46 UTC
**Describe the bug**

Changes permission of `/home/username/.aws-iot-device-client` directory to incorrect permissions (700 when it should be 745)
Creates runtime configuration file `/home/username/.aws-iot-device-client/aws-iot-device-client-runtime.conf` with incorrect permissions (644 when it should be 664)

**To Reproduce**

1. New project, build, setup.sh
2. Enable most resources, including provisioning
3. Cert & Key point to provisioning cert files
4. Do not install as service
5. Run ./aws-iot-device-client
6. File permission error with logs:
7. For sanity sake, set permissions correctly
chmod 745 /home/username/.aws-iot-device-client/
chmod 644 /home/username/.aws-iot-device-client/aws-iot-device-client-runtime.conf
8. re-run /aws-iot-device-client
9. still has permission error, and creates a new cert 

**Expected behavior**

Because `/home/username/.aws-iot-device-client/` already exists, it should not re-create it. 
If it creates it, it should be created with permission 745

`/home/username/.aws-iot-device-client/aws-iot-device-client-runtime.conf` should be created with 644

Should not crash with fatal error

**Actual behavior**

`/home/username/.aws-iot-device-client/` was changed to permission 700
`/home/username/.aws-iot-device-client/aws-iot-device-client-runtime.conf` was created with permission 664

**Logs**
Run 1
```
2022-07-22T19:04:19.789Z [WARN]  {Config.cpp}: Key {csr-file} was provided in the JSON configuration file with an empty value
2022-07-22T19:04:19.789Z [WARN]  {Config.cpp}: Key {device-key} was provided in the JSON configuration file with an empty value
2022-07-22T19:04:19.789Z [INFO]  {Config.cpp}: Successfully fetched JSON config file: 
    {
      "endpoint":       "my-endpoint",
      "cert":   "/aws-iot/keys/provisioning-certificate.pem.crt",
      "key":    "/aws-iot/keys/provisioning-private.pem.key",
      "root-ca":        "/aws-iot/keys/AmazonRootCA1.pem",
      "thing-name":     "my_device_name",
      "logging":        {
        "level":        "DEBUG",
        "type": "STDOUT",
        "file": "/var/log/aws-iot-device-client/aws-iot-device-client.log",
        "enable-sdk-logging":   false,
        "sdk-log-level":        "TRACE",
        "sdk-log-file": "/var/log/aws-iot-device-client/sdk.log"
      },
      "jobs":   {
        "enabled":      true,
        "handler-directory": "/aws-iot/jobs"
      },
      "tunneling":      {
        "enabled":      true
      },
      "device-defender":        {
        "enabled":      true,
        "interval": 300
      },
      "fleet-provisioning":     {
        "enabled":      true,
        "template-name": "DeviceProvisioning",
        "template-parameters": "my-json-parameters",
        "csr-file": "",
        "device-key": ""
      },
      "samples": {
        "pub-sub": {
          "enabled": true,
          "publish-topic": "arn:aws:iot:us-east-1:my-account:topic/pubsub/pub",
          "publish-file": "/aws-iot/pubsub/pub",
          "subscribe-topic": "arn:aws:iot:us-east-1:my-account:topic/pubsub/sub",
          "subscribe-file": "/aws-iot/pubsub/sub"
        }
      },
      "config-shadow":  {
        "enabled":      true
      },
      "sample-shadow": {
        "enabled": true,
        "shadow-name": "sample",
        "shadow-input-file": "/aws-iot/sampleshadow/in",
        "shadow-output-file": "/aws-iot/sampleshadow/out"
      }
    }

2022-07-22T19:04:19.789Z [INFO]  {FileUtils.cpp}: Successfully create directory /home/username/.aws-iot-device-client/sample-shadow/ with required permissions 700
2022-07-22T19:04:19.789Z [INFO]  {Config.cpp}: ~/.aws-iot-device-client/sample-shadow/default-sample-shadow-document
2022-07-22T19:04:19.789Z [INFO]  {Config.cpp}: Succesfully create default file: /home/username/.aws-iot-device-client/sample-shadow/default-sample-shadow-document required for storage of shadow document
2022-07-22T19:04:19.789Z [DEBUG] {Config.cpp}: Did not find a runtime configuration file, assuming Fleet Provisioning has not run for this device
2022-07-22T19:04:19.789Z [DEBUG] {Config.cpp}: Did not find a http proxy config file /home/username/.aws-iot-device-client/http-proxy.conf, assuming HTTP proxy is disabled on this device
2022-07-22T19:04:19.789Z [DEBUG] {EnvUtils.cpp}: Updated PATH environment variable to: /home/username/.nvm/versions/node/v16.16.0/bin:/home/username/.local/bin:/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/username/go/bin:/home/username/go/bin:/home/username/.aws-iot-device-client:/home/username/.aws-iot-device-client/jobs:/home/username/development/work/aws-iot-device-client/build:/home/username/development/work/aws-iot-device-client/build/jobs
2022-07-22T19:04:19.789Z [INFO]  {Main.cpp}: Now running AWS IoT Device Client version v1.6.29-d633b0a
2022-07-22T19:04:19.791Z [INFO]  {SharedCrtResourceManager.cpp}: SDK logging is disabled. Enable it with --enable-sdk-logging on the command line or logging::enable-sdk-logging in your configuration file
2022-07-22T19:04:19.791Z [DEBUG] {Retry.cpp}: Retryable function starting, it will retry until success
2022-07-22T19:04:19.799Z [INFO]  {SharedCrtResourceManager.cpp}: Establishing MQTT connection with client id my_device_name...
2022-07-22T19:04:20.395Z [INFO]  {SharedCrtResourceManager.cpp}: MQTT connection established with return code: 0
2022-07-22T19:04:20.395Z [INFO]  {SharedCrtResourceManager.cpp}: Shared MQTT connection is ready!
2022-07-22T19:04:20.396Z [INFO]  {FleetProvisioning.cpp}: Fleet Provisioning Feature has been started.
2022-07-22T19:04:20.396Z [INFO]  {FileUtils.cpp}: Successfully create directory /home/username/.aws-iot-device-client/keys/ with required permissions 700
2022-07-22T19:04:20.396Z [INFO]  {FileUtils.cpp}: Successfully create directory /home/username/.aws-iot-device-client/ with required permissions 700
2022-07-22T19:04:20.396Z [INFO]  {FleetProvisioning.cpp}: Provisioning new device certificate and private key using CreateKeysAndCertificate API
2022-07-22T19:04:20.396Z [INFO]  {FleetProvisioning.cpp}: Subscribing to CreateKeysAndCertificate Accepted and Rejected topics
2022-07-22T19:04:20.599Z [INFO]  {FleetProvisioning.cpp}: Publishing to CreateKeysAndCertificate topic
2022-07-22T19:04:21.219Z [INFO]  {FleetProvisioning.cpp}: CreateKeysAndCertificateResponse certificateId: generated-cert-id.
2022-07-22T19:04:21.219Z [INFO]  {FleetProvisioning.cpp}: Stored certificate and private key in /home/username/.aws-iot-device-client/keys/generated-cert-id-certificate.pem.crt and /home/username/.aws-iot-device-client/keys/generated-cert-id-private.pem.key files
2022-07-22T19:04:21.219Z [INFO]  {FleetProvisioning.cpp}: Attempting to set permissions for certificate and private key...
2022-07-22T19:04:21.219Z [INFO]  {FleetProvisioning.cpp}: Successfully set permissions on provisioned public certificate and private key
2022-07-22T19:04:21.220Z [INFO]  {FleetProvisioning.cpp}: Subscribing to RegisterThing Accepted and Rejected topics
2022-07-22T19:04:21.463Z [INFO]  {FleetProvisioning.cpp}: Publishing to RegisterThing topic
2022-07-22T19:04:23.325Z [INFO]  {FleetProvisioning.cpp}: RegisterThingResponse ThingName: my_device_name.
2022-07-22T19:04:23.325Z [INFO]  {FleetProvisioning.cpp}: Exported runtime configurations to: ~/.aws-iot-device-client/aws-iot-device-client-runtime.conf
2022-07-22T19:04:23.325Z [WARN]  {FileUtils.cpp}: Permissions to given file/dir path '/home/username/.aws-iot-device-client/aws-iot-device-client-runtime.conf' is not set to recommended value... {Permissions: {desired: 644, actual: 664}}
2022-07-22T19:04:23.325Z [INFO]  {FleetProvisioning.cpp}: Successfully provisioned thing: my_device_name
2022-07-22T19:04:23.325Z [ERROR] {FileUtils.cpp}: Permissions to given file/dir path '/home/username/.aws-iot-device-client/' is not set to required value... {Permissions: {desired: 745, actual: 700}}
2022-07-22T19:04:23.325Z [ERROR] {FileUtils.cpp}: Permissions to given file/dir path '/home/username/.aws-iot-device-client/aws-iot-device-client-runtime.conf' is not set to required value... {Permissions: {desired: 644, actual: 664}}
2022-07-22T19:04:23.326Z [INFO]  {Config.cpp}: Successfully fetched JSON config file: {
"runtime-config": {
    "completed-fp": true,
    "cert": "/home/username/.aws-iot-device-client/keys/generated-cert-id-certificate.pem.crt",
    "key": "/home/username/.aws-iot-device-client/keys/generated-cert-id-private.pem.key",
    "thing-name": "my_device_name",
    "device-config": {
        
        }
    }
} 
2022-07-22T19:04:23.326Z [ERROR] {Config.cpp}: Failed to Validate runtime configurations. Please check '~/.aws-iot-device-client/aws-iot-device-client-runtime.conf' file
2022-07-22T19:04:23.326Z [ERROR] {Main.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Failed to Provision thing or validate newly created resources. Please verify your AWS IoT credentials, configuration, Fleet Provisioning Template, claim certificate and policy used. ***
AWS IoT Device Client must abort execution, reason: Fleet provisioning failed
Please check the AWS IoT Device Client logs for more information
```
Run 2
```
2022-07-22T19:29:02.627Z [WARN]  {Config.cpp}: Key {csr-file} was provided in the JSON configuration file with an empty value
2022-07-22T19:29:02.627Z [WARN]  {Config.cpp}: Key {device-key} was provided in the JSON configuration file with an empty value
2022-07-22T19:29:02.627Z [INFO]  {Config.cpp}: Successfully fetched JSON config file: 
    {
      "endpoint":       "my-endpoint",
      "cert":   "/aws-iot/keys/provisioning-certificate.pem.crt",
      "key":    "/aws-iot/keys/provisioning-private.pem.key",
      "root-ca":        "/aws-iot/keys/AmazonRootCA1.pem",
      "thing-name":     "my_device_name",
      "logging":        {
        "level":        "DEBUG",
        "type": "STDOUT",
        "file": "/var/log/aws-iot-device-client/aws-iot-device-client.log",
        "enable-sdk-logging":   false,
        "sdk-log-level":        "TRACE",
        "sdk-log-file": "/var/log/aws-iot-device-client/sdk.log"
      },
      "jobs":   {
        "enabled":      true,
        "handler-directory": "/aws-iot/jobs"
      },
      "tunneling":      {
        "enabled":      true
      },
      "device-defender":        {
        "enabled":      true,
        "interval": 300
      },
      "fleet-provisioning":     {
        "enabled":      true,
        "template-name": "DeviceProvisioning",
        "template-parameters": "my-json-parameters",
        "csr-file": "",
        "device-key": ""
      },
      "samples": {
        "pub-sub": {
          "enabled": true,
          "publish-topic": "arn:aws:iot:us-east-1:my-account:topic/pubsub/pub",
          "publish-file": "/aws-iot/pubsub/pub",
          "subscribe-topic": "arn:aws:iot:us-east-1:my-account:topic/pubsub/sub",
          "subscribe-file": "/aws-iot/pubsub/sub"
        }
      },
      "config-shadow":  {
        "enabled":      true
      },
      "sample-shadow": {
        "enabled": true,
        "shadow-name": "sample",
        "shadow-input-file": "/aws-iot/sampleshadow/in",
        "shadow-output-file": "/aws-iot/sampleshadow/out"
      }
    }

2022-07-22T19:29:02.627Z [INFO]  {FileUtils.cpp}: Successfully create directory /home/username/.aws-iot-device-client/sample-shadow/ with required permissions 700
2022-07-22T19:29:02.627Z [INFO]  {Config.cpp}: ~/.aws-iot-device-client/sample-shadow/default-sample-shadow-document
2022-07-22T19:29:02.627Z [INFO]  {Config.cpp}: Succesfully create default file: /home/username/.aws-iot-device-client/sample-shadow/default-sample-shadow-document required for storage of shadow document
2022-07-22T19:29:02.627Z [INFO]  {Config.cpp}: Successfully fetched JSON config file: {
"runtime-config": {
    "completed-fp": true,
    "cert": "/home/username/.aws-iot-device-client/keys/generated-cert-id-certificate.pem.crt",
    "key": "/home/username/.aws-iot-device-client/keys/generated-cert-id-private.pem.key",
    "thing-name": "my_device_name",
    "device-config": {
        
        }
    }
} 
2022-07-22T19:29:02.627Z [ERROR] {Config.cpp}: Failed to Validate runtime configurations. Please check '~/.aws-iot-device-client/aws-iot-device-client-runtime.conf' file
2022-07-22T19:29:02.627Z [DEBUG] {Config.cpp}: Did not find a http proxy config file /home/username/.aws-iot-device-client/http-proxy.conf, assuming HTTP proxy is disabled on this device
2022-07-22T19:29:02.627Z [DEBUG] {EnvUtils.cpp}: Updated PATH environment variable to: /home/username/.nvm/versions/node/v16.16.0/bin:/home/username/.local/bin:/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/username/go/bin:/home/username/go/bin:/home/username/.aws-iot-device-client:/home/username/.aws-iot-device-client/jobs:/home/username/development/work/aws-iot-device-client/build:/home/username/development/work/aws-iot-device-client/build/jobs
2022-07-22T19:29:02.627Z [INFO]  {Main.cpp}: Now running AWS IoT Device Client version v1.6.29-d633b0a
2022-07-22T19:29:02.629Z [INFO]  {SharedCrtResourceManager.cpp}: SDK logging is disabled. Enable it with --enable-sdk-logging on the command line or logging::enable-sdk-logging in your configuration file
2022-07-22T19:29:02.630Z [DEBUG] {Retry.cpp}: Retryable function starting, it will retry until success
2022-07-22T19:29:02.637Z [INFO]  {SharedCrtResourceManager.cpp}: Establishing MQTT connection with client id my_device_name...
2022-07-22T19:29:03.223Z [INFO]  {SharedCrtResourceManager.cpp}: MQTT connection established with return code: 0
2022-07-22T19:29:03.223Z [INFO]  {SharedCrtResourceManager.cpp}: Shared MQTT connection is ready!
2022-07-22T19:29:03.224Z [INFO]  {FleetProvisioning.cpp}: Fleet Provisioning Feature has been started.
2022-07-22T19:29:03.224Z [INFO]  {FileUtils.cpp}: Successfully create directory /home/username/.aws-iot-device-client/keys/ with required permissions 700
2022-07-22T19:29:03.224Z [INFO]  {FileUtils.cpp}: Successfully create directory /home/username/.aws-iot-device-client/ with required permissions 700
2022-07-22T19:29:03.224Z [INFO]  {FleetProvisioning.cpp}: Provisioning new device certificate and private key using CreateKeysAndCertificate API
2022-07-22T19:29:03.224Z [INFO]  {FleetProvisioning.cpp}: Subscribing to CreateKeysAndCertificate Accepted and Rejected topics
2022-07-22T19:29:03.402Z [INFO]  {FleetProvisioning.cpp}: Publishing to CreateKeysAndCertificate topic
2022-07-22T19:29:04.064Z [INFO]  {FleetProvisioning.cpp}: CreateKeysAndCertificateResponse certificateId: new-cert-id.
2022-07-22T19:29:04.065Z [INFO]  {FleetProvisioning.cpp}: Stored certificate and private key in /home/username/.aws-iot-device-client/keys/new-cert-id-certificate.pem.crt and /home/username/.aws-iot-device-client/keys/new-cert-id-private.pem.key files
2022-07-22T19:29:04.065Z [INFO]  {FleetProvisioning.cpp}: Attempting to set permissions for certificate and private key...
2022-07-22T19:29:04.065Z [INFO]  {FleetProvisioning.cpp}: Successfully set permissions on provisioned public certificate and private key
2022-07-22T19:29:04.065Z [INFO]  {FleetProvisioning.cpp}: Subscribing to RegisterThing Accepted and Rejected topics
2022-07-22T19:29:04.245Z [INFO]  {FleetProvisioning.cpp}: Publishing to RegisterThing topic
2022-07-22T19:29:06.132Z [INFO]  {FleetProvisioning.cpp}: RegisterThingResponse ThingName: my_device_name.
2022-07-22T19:29:06.132Z [INFO]  {FleetProvisioning.cpp}: Exported runtime configurations to: ~/.aws-iot-device-client/aws-iot-device-client-runtime.conf
2022-07-22T19:29:06.132Z [INFO]  {FleetProvisioning.cpp}: Successfully provisioned thing: my_device_name
2022-07-22T19:29:06.132Z [ERROR] {FileUtils.cpp}: Permissions to given file/dir path '/home/username/.aws-iot-device-client/' is not set to required value... {Permissions: {desired: 745, actual: 700}}
2022-07-22T19:29:06.132Z [INFO]  {Config.cpp}: Successfully fetched JSON config file: {
"runtime-config": {
    "completed-fp": true,
    "cert": "/home/username/.aws-iot-device-client/keys/new-cert-id-certificate.pem.crt",
    "key": "/home/username/.aws-iot-device-client/keys/new-cert-id-private.pem.key",
    "thing-name": "my_device_name",
    "device-config": {
        
        }
    }
} 
2022-07-22T19:29:06.132Z [ERROR] {Config.cpp}: Failed to Validate runtime configurations. Please check '~/.aws-iot-device-client/aws-iot-device-client-runtime.conf' file
2022-07-22T19:29:06.132Z [ERROR] {Main.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Failed to Provision thing or validate newly created resources. Please verify your AWS IoT credentials, configuration, Fleet Provisioning Template, claim certificate and policy used. ***
AWS IoT Device Client must abort execution, reason: Fleet provisioning failed
Please check the AWS IoT Device Client logs for more information
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04
 - Architecture: x86-64
 - Device Client commit: https://github.com/awslabs/aws-iot-device-client/commit/d633b0a1225e4189b2750eadbb4bca2a8f310e87

**Additional context**

Side note, it probably shouldn't be creating /home/username/.aws-iot-device-client/sample-shadow since I have a different directory specified in the config.

Side note 2, the runtime config has an invalid utf8 character at the end that causes it to fail to load.
[aws-iot-device-client-runtime.zip](https://github.com/awslabs/aws-iot-device-client/files/9172086/aws-iot-device-client-runtime.zip)

**Comment by HarshGandhi-AWS** [comment] 2022-07-22 20:25
Hello @JustinBerger , thank you for bringing this issue to our attention. I was able to reproduce this issue and can confirm this bug is present in fleet provisioning feature. Please be patient with us until we find and resolve this issue. 

Regards, 
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment] 2022-07-26 17:02
Hello @JustinBerger , I was able to resolve the issue you were facing earlier last week. The latest version of Device Client on main branch is now merged with the fix. Please let us know if you are still facing the issue or if come across any other issue while using the client and we would be more than happy to assist you to resolve the issue. 

Regards, 
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment] 2022-07-26 17:18
Hey @JustinBerger , I am reopening this issue since I missed few comments from you on `/home/username/.aws-iot-device-client/` and `/home/username/.aws-iot-device-client/sample-shadow` directory creation. Taking a look at it now.

**Comment by JustinBerger** [comment] 2022-07-27 18:50
Looks like the sample-shadow issue is because PlainConfig::SampleShadow::createShadowOutputFile() is overwriting the specified output file with the default values.

If you specify the directory via configs it skips calling that endpoint.
But then later on when it loads the CLI Args, it's not getting an output file and running that method anyways, overwriting the config set via json.

**Comment by HarshGandhi-AWS** [comment] 2022-07-27 19:02
Yes. I saw that. I have removed that part from json and cli config loading functions. Will test and have a new PR for it in sometime. :)

**Comment by HarshGandhi-AWS** [comment] 2022-07-29 23:59
Hello @JustinBerger , in my last PR I have addressed the rest of the issues you had mentioned in this ticket. Please let me know if the fix works for you or not and feel free to open new issue with us if required. 

Regards,
Harsh Gandhi

**Closed by HarshGandhi-AWS** 2022-07-29 23:59 UTC
Labels: bug
