### ISSUE TITLE
posix_memalign failed to allocate memory

### ISSUE THREAD

**Issue by make-ing** [awslabs/aws-iot-device-client#434] opened 2023-10-27 08:12 UTC
**Describe the bug**

The client immediately crashes after loading the configuration file with the following error message:
`posix_memalign failed to allocate memoryAborted (core dumped)`

**To Reproduce**

1. clone the repo
2. build the client
3. setup a default configuration
4. run the client

**Expected behavior**

I expect the client to keep running without any errors.

**Actual behavior**

The client immediately crashes we the above mentioned error.

**Logs**

N/A

**Environment (please complete the following information):**
Local notebook:
 - OS: Ubuntu
 - Version: 22.04
 - Architecture: x86-64

Raspberry Pi CM4:
 - OS: Raspbian (Debian)
  - Version: 12
 - Architecture: aarch64

source version:
 - Device Client commit: [2efead687fd4d7a1172e5ea7e193406cc51f59c7](https://github.com/awslabs/aws-iot-device-client/commit/2efead687fd4d7a1172e5ea7e193406cc51f59c7)

**Additional context**

I tested it on the Raspberry Pi CM4 and my own Notebook running Ubuntu 22.04 as well as in the docker container all with the same results.

Config file:
```
{
      "endpoint":	"<REDACTED>.iot.eu-central-1.amazonaws.com",
      "cert":	"~/iot-client-tempt/certs/public",
      "key":	"~/iot-client-tempt/certs/private",
      "root-ca":	"~/iot-client-tempt/certs/root",
      "thing-name":	"<REDACTED>",
      "logging":	{
        "level":	"DEBUG",
        "type":	"FILE",
        "file": "/var/log/aws-iot-device-client/aws-iot-device-client.log",
        "enable-sdk-logging":	false,
        "sdk-log-level":	"TRACE",
        "sdk-log-file": "/var/log/aws-iot-device-client/sdk.log"
      },
      "jobs":	{
        "enabled":	true,
        "handler-directory": "/home/florian/.aws-iot-device-client/jobs"
      },
      "tunneling":	{
        "enabled":	true
      },
      "device-defender":	{
        "enabled":	false,
        "interval": 300
      },
      "fleet-provisioning":	{
        "enabled":	false,
        "template-name": "",
        "template-parameters": "",
        "csr-file": "",
        "device-key": ""
      },
      "samples": {
        "pub-sub": {
          "enabled": false,
          "publish-topic": "",
          "publish-file": "/home/florian/.aws-iot-device-client/pubsub/publish-file.txt",
          "subscribe-topic": "",
          "subscribe-file": "/home/florian/.aws-iot-device-client/pubsub/subscribe-file.txt"
        }
      },
      "config-shadow":	{
        "enabled":	false
      },
      "sample-shadow": {
        "enabled": false,
        "shadow-name": "",
        "shadow-input-file": "",
        "shadow-output-file": ""
      }
    }
```

**Comment by HarshGandhi-AWS** [comment] 2024-01-22 19:40
Hello @make-ing , last month in December we released a newer version of Device Client which resolves multiple pending issue like the one you have mentioned over here. Can you update the client version on your device and use the latest commit to see if the issue is resolved for you or not? 

Regards,
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment] 2024-02-02 20:56
Hello @make-ing  , its been a while since we heard back from you. We will close this issue now. I hope the previous comment answers your question and you are unblocked now. 
If you have any other question regarding Device Client or if you are having any trouble using the software then please feel free to reopen this issue or create a new one.

Regards,
Harsh Gandhi

**Closed by HarshGandhi-AWS** 2024-02-02 20:56 UTC
Labels: bug
