### ISSUE TITLE
Add sdk logging configuration to config template

### ISSUE THREAD

**Issue by rpcme** [awslabs/aws-iot-device-client#178] opened 2021-10-16 11:29 UTC
**Is your feature request related to a problem? Please describe.**

SDK logging is not defined in the config template https://github.com/awslabs/aws-iot-device-client/blob/main/config-template.json

**Describe the solution you'd like**
Please represent SDK logging defined here
https://github.com/awslabs/aws-iot-device-client/blob/main/source/logging/README.md#configuring-sdk-logging-via-the-json-configuration-file
in the sample JSON config file

**Describe alternatives you've considered**

None that I can think of

**Additional context**

**Comment by HarshGandhi-AWS** [comment] 2021-12-14 16:45
Hello @rpcme  , again thank you for reaching out to us with this issue. @xlcheng1 and @marcoemorais-aws has released the bug fix for this issue. Please review and test it to see if the issue is resolved for you or not.
I am resolving this issue now, please feel free to reopen it if the issue is not resolved or open a new issue with us if you are facing any difficulty using the Device Client.

Regards,
Harsh Gandhi

**Closed by HarshGandhi-AWS** 2021-12-14 16:45 UTC
Labels: enhancement
