### ISSUE TITLE
LockFile Error (Device Client is already running.)

### ISSUE THREAD

**Issue by nishida1023** [awslabs/aws-iot-device-client#418] opened 2023-06-19 11:23 UTC
**Describe the bug**
LockFile Error

**To Reproduce**
Start aws-iot-device-client before fleet provisioning is completed.

**Expected behavior**

aws-iot-device-client does not stop.

**Actual behavior**

aws-iot-device-client stopped with an error.

**Logs**

```
2023-06-19T11:10:22.203Z [DEBUG] {SharedCrtResourceManager.cpp}: Attempting to disconnect MQTT connection
2023-06-19T11:10:22.216Z [INFO]  {SharedCrtResourceManager.cpp}: MQTT Connection is now disconnected
2023-06-19T11:10:22.216Z [DEBUG] {LockFile.cpp}: creating lockfile
2023-06-19T11:10:22.216Z [ERROR] {LockFile.cpp}: Pid 42199 associated with active process ./aws-iot-device-client in lockfile: /run/lock/devicecl.lock
2023-06-19T11:10:22.219Z [ERROR] {Main.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Error obtaining lockfile: Device Client is already running.
2023-06-19T11:10:22.219Z [ERROR] {Main.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: An instance of Device Client is already running.
2023-06-19T11:10:22.219Z [DEBUG] {SharedCrtResourceManager.cpp}: Attempting to disconnect MQTT connection
2023-06-19T11:10:22.219Z [ERROR] {SharedCrtResourceManager.cpp}: MQTT Connection failed to disconnect
AWS IoT Device Client must abort execution, reason: An instance of Device Client is already running.
Please check the AWS IoT Device Client logs for more information
```

**Environment (please complete the following information):**
OS: Ubuntu
Version 22.04.1
Architecture: x86_64
Device Client commit: 239d10d968eb635d883998ff70e5054e66aef450

**Additional context**
If fleet provisioning has not been completed, the reason for the error is that init() is called twice.
https://github.com/awslabs/aws-iot-device-client/pull/391/files

**Comment by HarshGandhi-AWS** [comment] 2023-06-20 17:36
Hello @nishida1023 , can you share complete logs with config passed? Just by looking at the logs you shared, it is difficult to understand what is the issue. Also what do you mean by " Start aws-iot-device-client before fleet provisioning is completed."? Can you share exact steps to reproduce the issue?

**Comment by HarshGandhi-AWS** [comment] 2023-06-20 17:50
Also it looks like there is a bug in our code. With Fleet Provisioning enabled, we are calling `init()` twice which will cause DC abort. 
https://github.com/awslabs/aws-iot-device-client/blob/main/source/main.cpp#L354-L358
https://github.com/awslabs/aws-iot-device-client/blob/main/source/main.cpp#L354-L358

**Comment by nishida1023** [comment] 2023-06-21 08:45
@HarshGandhi-AWS 
Sorry my English is not good.

> Also what do you mean by " Start aws-iot-device-client before fleet provisioning is completed."?

If completed-fp in aws-iot-device-client-runtime.conf is true, no bug occurs, but if false, a bug occurs.

> Also it looks like there is a bug in our code. With Fleet Provisioning enabled, we are calling init() twice which will cause DC abort.

I noticed this bug and created an ISSUE. This bug is included in the latest main branch.

**Comment by HarshGandhi-AWS** [comment] 2023-06-29 16:41
Hello @nishida1023 , thank you for sharing details. 
As I suspected, this issue happens when Fleet Provisioning feature is enabled. I will work on resolving this issue today. 

To unblock yourself from using device client, I would suggest disabling Fleet Provisioning feature via config and starting the device client again. If you want to use Fleet Provisioning, then unfortunately there is no workaround and you will have to wait until the bug is fixed.

**Comment by HarshGandhi-AWS** [comment] 2023-06-29 23:52
Hello @nishida1023 , this issue is been resolved in the latest commit. 

I will close this issue now, feel free to reopen this issue or create a new one if you still face any difficulty using Device Client. Thank you.

**Closed by HarshGandhi-AWS** 2023-06-29 23:52 UTC
Labels: bug

**Comment by nishida1023** [comment] 2023-06-30 05:03
@HarshGandhi-AWS 
Thank you for resolving the issue!
