### ISSUE TITLE
AWS_ERROR_MQTT_UNEXPECTED_HANGUP after 2 min of runtime

### ISSUE THREAD

**Issue by dsoltysiuk** [awslabs/aws-iot-device-client#412] opened 2023-05-16 16:49 UTC
**Describe the bug**
After 2min of running the AWS Device Client, this error pops up and keeps popping up every 2 mins since
```
May 16 09:30:14 raspberrypi aws-iot-device-client[1539]: 2023-05-16T16:30:14.649Z [ERROR] {SharedCrtResourceManager.cpp}: MQTT Connection interrupted with error: `libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.`. Device Client will retry connection until it is successfully connected to the core.
May 16 09:30:15 raspberrypi aws-iot-device-client[1539]: 2023-05-16T16:30:15.160Z [INFO]  {SharedCrtResourceManager.cpp}: MQTT connection resumed with return code: 0
```

Just so you know, the first 2mins device client works and I can successfully establish tunnels and jobs.

**To Reproduce**
1. Install the device client
2. Configure it with Jobs and Secure Tunneling feature
3. Run it and wait 2 minutes

**Expected behavior**
The error should not happen.

**Actual behavior**
The error pops up every 2 mins, remote actions do not take place as a result.

**Logs**
Device client logs: https://pastebin.com/r6d5BZbB
SDK logs: https://pastebin.com/9d145Wm5

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Version: Debian version: 11 (bullseye)
 - Architecture: ARM (32/64 bit)
 - Device Client commit: https://github.com/awslabs/aws-iot-device-client/commit/4bc8c2a4a4a745c2abbe8c9c433557bba42fbc76

**Additional context**

**Comment by HarshGandhi-AWS** [comment] 2023-05-30 16:19
Hello @dsoltysiuk thank you for reaching out to us. The device client behavior you explained happens when the device internet connection is not strong and connection keeps dropping after sometime. 

Still give us sometime to go through complete logs to see if there is any issue on DC side causing connection drop.

**Comment by HarshGandhi-AWS** [comment] 2023-10-06 21:06
Hello @dsoltysiuk , we were not able to reproduce this issue. It is likely the error you have got was because of bad internet connection or interruption. 

Closing this issue now. Please feel free to reopen if you are still facing this issue.

**Closed by HarshGandhi-AWS** 2023-10-06 21:06 UTC
Labels: bug
