### ISSUE TITLE
Cannot connect to secure tunnel when running the iot-device-client from docker

### ISSUE THREAD

**Issue by alonsnir** [awslabs/aws-iot-device-client#454] opened 2024-04-17 09:19 UTC
**Destination state remain Disconnected**

Device client is running, secure tunnel to the thing been created, but fails to connect
**To Reproduce**
docker run -it -v /home/alon/.arugga/iot:/iot public.ecr.aws/aws-iot-device-client/aws-iot-device-client:x86_64-ubuntu-v1.8.40-da10323 --config-file /iot/iot-config/aws-iot-device-client.conf 
2024-04-17T08:57:05.872Z [INFO]  {Config.cpp}: Successfully fetched JSON config file: 
    {
      "endpoint":	"#############ats.iot.eu-central-1.amazonaws.com",
      "cert":	"/iot/iot-certs/10001-certificate.pem.crt",
      "key":	"/iot/iot-certs/10001-private.pem.key",
      "root-ca":	"/iot/iot-certs/AmazonRootCA1.pem",
      "thing-name":	"10001",
      "logging":	{
        "level":	"DEBUG",
        "type":	"STDOUT",
        "file": "/var/log/aws-iot-device-client/aws-iot-device-client.log",
        "enable-sdk-logging":	true,
        "sdk-log-level":	"DEBUG",
        "sdk-log-file": "/var/log/aws-iot-device-client/sdk.log"
      },
      "jobs":	{
        "enabled":	false,
        "handler-directory": "/iot/jobs"
      },
      "tunneling":	{
        "enabled":	true
      },
      "device-defender":	{
        "enabled":	false,
        "interval": 300
      },
      "fleet-provisioning":	{
        "enabled":	false,
        "template-name": "",
        "template-parameters": "",
        "csr-file": "",
        "device-key": ""
      },
      "samples": {
        "pub-sub": {
          "enabled": false,
          "publish-topic": "",
          "publish-file": "/iot/.aws-iot-device-client/pubsub/publish-file.txt",
          "subscribe-topic": "",
          "subscribe-file": "/iot/.aws-iot-device-client/pubsub/subscribe-file.txt"
        }
      },
      "config-shadow":	{
        "enabled":	false
      },
      "sample-shadow": {
        "enabled": false,
        "shadow-name": "",
        "shadow-input-file": "",
        "shadow-output-file": ""
      }
    }

2024-04-17T08:57:05.873Z [INFO]  {FileUtils.cpp}: Successfully create directory /root/.aws-iot-device-client/sample-shadow/ with required permissions 700
2024-04-17T08:57:05.873Z [INFO]  {Config.cpp}: ~/.aws-iot-device-client/sample-shadow/default-sample-shadow-document
2024-04-17T08:57:05.873Z [INFO]  {Config.cpp}: Succesfully create default file: /root/.aws-iot-device-client/sample-shadow/default-sample-shadow-document required for storage of shadow document
2024-04-17T08:57:05.873Z [DEBUG] {Config.cpp}: Did not find a runtime configuration file, assuming Fleet Provisioning has not run for this device
2024-04-17T08:57:05.873Z [DEBUG] {Config.cpp}: Did not find a http proxy config file /root/.aws-iot-device-client/http-proxy.conf, assuming HTTP proxy is disabled on this device
2024-04-17T08:57:05.873Z [DEBUG] {EnvUtils.cpp}: Updated PATH environment variable to: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.aws-iot-device-client:/root/.aws-iot-device-client/jobs:/://jobs
2024-04-17T08:57:05.873Z [DEBUG] {LockFile.cpp}: creating lockfile
2024-04-17T08:57:05.874Z [INFO]  {Main.cpp}: Now running AWS IoT Device Client version v1.8.40-da10323
2024-04-17T08:57:05.874Z [INFO]  {FileUtils.cpp}: Successfully create directory /var/log/aws-iot-device-client/ with required permissions 745
2024-04-17T08:57:05.874Z [INFO]  {SharedCrtResourceManager.cpp}: SDK logging is enabled. Check /var/log/aws-iot-device-client/sdk.log for SDK logs.
2024-04-17T08:57:05.875Z [DEBUG] {Retry.cpp}: Retryable function starting, it will retry until success
2024-04-17T08:57:05.879Z [INFO]  {SharedCrtResourceManager.cpp}: Establishing MQTT connection with client id 10001...
2024-04-17T08:57:06.281Z [INFO]  {SharedCrtResourceManager.cpp}: MQTT connection established with return code: 0
2024-04-17T08:57:06.281Z [INFO]  {SharedCrtResourceManager.cpp}: Shared MQTT connection is ready!
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Provisioning with Secure Elements is disabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Config shadow is disabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Jobs is disabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Secure Tunneling is enabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Device Defender is disabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Sample shadow is disabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Pub Sub is disabled
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Sensor Publish is disabled
2024-04-17T08:57:06.281Z [INFO]  {SharedCrtResourceManager.cpp}: Starting Device Client features.
2024-04-17T08:57:06.281Z [DEBUG] {FeatureRegistry.cpp}: Attempting to start Secure Tunneling
2024-04-17T08:57:06.281Z [INFO]  {SecureTunnelingFeature.cpp}: Running Secure Tunneling!
2024-04-17T08:57:06.281Z [INFO]  {Main.cpp}: Client base has been notified that Secure Tunneling has started
2024-04-17T08:57:06.335Z [DEBUG] {SecureTunnelingFeature.cpp}: Subscribed to tunnel notification topic
2024-04-17T09:06:00.706Z [DEBUG] {SecureTunnelingFeature.cpp}: Received MQTT Tunnel Notification
2024-04-17T09:06:00.706Z [DEBUG] {SecureTunnelingFeature.cpp}: Region=eu-central-1, Service=SSH
2024-04-17T09:06:01.061Z [DEBUG] {SecureTunnelingContext.cpp}: SecureTunnelingContext::OnConnectionComplete
2024-04-17T09:06:29.626Z [DEBUG] {SecureTunnelingContext.cpp}: SecureTunnelingContext::OnStreamStart
2024-04-17T09:06:29.626Z [DEBUG] {TcpForward.cpp}: TcpForward::OnConnectionResult
2024-04-17T09:06:29.626Z [ERROR] {TcpForward.cpp}: TcpForward::OnConnectionResult error_code=1047
2024-04-17T09:06:35.544Z [DEBUG] {SecureTunnelingContext.cpp}: SecureTunnelingContext::OnDataReceive data.len=16
2024-04-17T09:06:35.544Z [DEBUG] {TcpForward.cpp}: Not connected yet. Saving the data to send
2024-04-17T09:06:59.627Z [DEBUG] {SecureTunnelingContext.cpp}: SecureTunnelingContext::OnDataReceive data.len=16
2024-04-17T09:06:59.627Z [DEBUG] {TcpForward.cpp}: Not connected yet. Saving the data to send
2024-04-17T09:07:05.785Z [DEBUG] {SecureTunnelingContext.cpp}: SecureTunnelingContext::OnDataReceive data.len=16
2024-04-17T09:07:05.785Z [DEBUG] {TcpForward.cpp}: Not connected yet. Saving the data to send
2024-04-17T09:07:29.080Z [DEBUG] {SecureTunnelingFeature.cpp}: Received MQTT Tunnel Notification
2024-04-17T09:07:29.080Z [DEBUG] {SecureTunnelingFeature.cpp}: Region=eu-central-1, Service=SSH
2024-04-17T09:07:29.429Z [DEBUG] {SecureTunnelingContext.cpp}: SecureTunnelingContext::OnConnectionComplete

**On the client side**
Using the AWS Iot console, I'm creating a tunnel to the thing, then when i try to connect to it it via the SSH (on the iot console) it doesn't let me. 
Destination connection state
Disconnected

What user name should I select when running Docker? I have selected ubuntu, but what it was just a guess. I'm not connecting to the device directly by via running the docker container.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 22
 - Architecture x86-64
 - Device Client commit:public.ecr.aws/aws-iot-device-client/aws-iot-device-client:x86_64-ubuntu-v1.8.40-da10323

**Additional context**

**Comment by HarshGandhi-AWS** [comment] 2024-04-24 01:00
Hello @alonsnir , I noticed you are using an older version of the Device Client. In v1.9 release, we did resolve some Secure Tunneling issues and bugs from both client and SDK side. Can you try using the newer released docker file? As of today, this is the the lattest version of docker image on our ecr repository. 

`public.ecr.aws/aws-iot-device-client/aws-iot-device-client:x86_64-ubuntu-v1.9.1-e3c0841`

Please let us know if upgrading to newer version of the client resolves the issue or not. 

Regards,
Harsh Gandhi

**Comment by alonsnir** [comment] 2024-04-24 13:08
Hello @HarshGandhi-AWS, thanks for getting back.
I'm will be happy to upgrade and test, but there is a more general question regarding the ssh feature.
Consider the following setup:
host ubuntu
it runs docker aws-iot-device-client
via the volumes I'm giving the docker to access jobs folders, so here all looks set, what I do not understand is how to I get it work with the ssh. I open the secure tunnel to the client on docker, how do i ssh into it? How do I ssh from it into the host?
Thanks

**Comment by HarshGandhi-AWS** [comment] 2024-04-25 19:50
Hello @alonsnir , I would recommend you going through this docker documentation explaining the networking details of docker container and the host running it. https://docs.docker.com/network/

In simple words, start your docker container by passing the `--network=host` in the run command. Once you do that, container will start forwarding all the network packets coming to container to the host machine network and then you can access the host machine even if your secure tunneling application is running on a docker conatiner on the destination device. 

Your docker command should look like this now: 

```
docker run -it --network=host -v /home/alon/.arugga/iot:/iot public.ecr.aws/aws-iot-device-client/aws-iot-device-client:x86_64-ubuntu-v1.9.1-e3c0841 --config-file /iot/iot-config/aws-iot-device-client.conf
```

I hope this helps. 

Also, may we know why are you running device client inside an docker container on an ubuntu host machine? Device Client works on ubuntu and you can directly run it on the ununtu host.

**Comment by HarshGandhi-AWS** [comment] 2024-04-29 21:36
I am closing this issue now. Let us know if you are still facing this issue or feel free to create a new issue if are facing any other issue using device client.

**Closed by HarshGandhi-AWS** 2024-04-29 21:36 UTC
Labels: bug

**Comment by anh193** [comment] 2025-04-03 08:45
@HarshGandhi-AWS I am now facing similar issue as the OP's, so `TcpForward error_code 1047`, even though I have this `network` flag used in the command. Any clue how to debug it further?

**Comment by ig15** [comment] 2025-04-07 07:08
Hi @anh193 . The error code in `TcpForward error_code 1047` resolves to [AWS_IO_SOCKET_CONNECTION_REFUSED](https://github.com/awslabs/aws-c-io/blob/9678fcec01c21bb98e86c957367448d4e3695880/include/aws/io/io.h#L115) from [aws-c-io](https://github.com/awslabs/aws-c-io/tree/9678fcec01c21bb98e86c957367448d4e3695880). This mostly occurs when the device does not meet the required specifications of device client. Specifically can you check if the secure tunneling endpoint is reachable i.e. outbound traffic on port 443 is open? 
Your remote device’s firewall must allow outbound traffic on port 443 in order for it to connect to the port 443 of the AWS IOT Core Tunnel.

If this does not resolve your issue, I'd suggest to open a new issue on the repo with the details of the issue and concerned logs for further investigation. Thank you.

**Comment by anh193** [comment] 2025-04-07 10:09
@ig15 thanks for your response.

Yes traffic should be properly configured. Just to make sure that the tunnelling is possible, my setup is as such:
- Edge device running Windows with WSL enabled
- `aws-iot-device-client` container run within a Docker container inside WSL Ubuntu.
- Outbound traffic is allowed on port 443 in Ubuntu
- WSL network is mirrored

**Comment by ig15** [comment] 2025-04-07 20:40
@anh193 The points mentioned by you are correct. Additionally please refer to our [documentation](https://github.com/awslabs/aws-iot-device-client/blob/main/README.md) for more details on the requirements. 

Are you still facing the issue? If yes, then please open a new issue with details as mentioned previously along with the required steps for reproduction of the issue.

**Comment by anh193** [comment] 2025-04-08 06:55
@ig15 I double-checked every component and the issue is now resolved, thank you for the support!

**Comment by ig15** [comment] 2025-04-08 07:04
No problem, thanks for the update.
