### ISSUE TITLE
c-format rules are unknown to contributors

### ISSUE THREAD

**Issue by philcali** [awslabs/aws-iot-device-client#331] opened 2022-09-22 21:29 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I was providing a pull request, getting the c-format lint workflow to be happy with my proposal was kind of like a guessing game. I was wondering if there was a way contributors could "self resolve" these issues more clearly than "source/SuchAndSuch.cpp failed"

**Describe the solution you'd like**
Would like to get instructions on how to match the lint rules tested against the repo and clearly resolve the issues encountered.

**Describe alternatives you've considered**
I built the lint container. Unfortunately I've found that the clang-format output is not great. I'm a mere mortal and need clear lint error codes.

**Additional context**

**Comment by xlcheng1** [comment] 2022-09-22 21:57
Hi @philcali , Thank you for reaching out! You can actually use one of the pre-built docker image available in our `packages` to run lint format check and fix them. Here are the steps:

1. run the docker image on top of your local repo:
```
    docker run --rm -it \
            -v $(pwd):/src \
            --workdir /src \
            --entrypoint /bin/bash \
            ghcr.io/awslabs/aws-iot-device-client/ubuntu-18-x64:latest
```
2. Have clang-format emit a copy of the source file formatted according to the rules.  In the example below, the cleanly formatted file is named `tmp`
`   clang-format <input-source-file>  > tmp`
4. Use diff to compare the cleanly formatted file with the current source file.
    `diff <input-source-file> tmp`
5. If you are satisfied with the changes suggested by clang format, overwrite the source file with tmp . In order to avoid losing your work, I recommend that you save the current revision of <input-source-file> with git before you overwrite the file.
`mv tmp <input-source-file>`
6. Run the format script again to confirm that the issue is resolved. Commit the updated revision.
`./format-check.sh`

**Comment by philcali** [comment] 2022-09-23 21:27
Ah ha! This is exactly what I was looking for! Thanks @xlcheng1. Is this something that could live in the README or reference from the README in the contribution section? It would save other like me (and future me) having to figure out this sequence again.

**Comment by xlcheng1** [comment] 2022-09-23 22:03
Thank you for the suggestion! I will work with my team on this. I am closing this issue for now and feel free to reopen if you have further questions.

**Closed by xlcheng1** 2022-09-23 22:03 UTC
Labels: enhancement
